# Matrices and Vectors in Python

In [1]:
import numpy as np
import pandas as pd

In [3]:
A = np.arange(21,30)
A

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
A = np.arange(21,30).reshape(3,3)
A

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [5]:
A.transpose()

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [6]:
10*A

array([[210, 220, 230],
       [240, 250, 260],
       [270, 280, 290]])

In [7]:
B = np.arange(31,40).reshape(3,3)

In [12]:
AB =A.dot(B)
AB

array([[2250, 2316, 2382],
       [2556, 2631, 2706],
       [2862, 2946, 3030]])

In [11]:
BA =B.dot(A)
BA

array([[2310, 2406, 2502],
       [2526, 2631, 2736],
       [2742, 2856, 2970]])

In [13]:
C = np.arange(41,50).reshape(3,3)

In [14]:
temp1 = (A.dot(B)).dot(C)
temp1

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

In [15]:
temp2 = A.dot(B.dot(C))
temp2

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

In [16]:
arr = np.arange(100,116).reshape(4,4)
arr

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [17]:
#determinant
np.linalg.det(arr)

-2.4233807008390354e-27

In [20]:
arr = np.arange(1,10).reshape(3,3)
np.linalg.eig(arr)

(array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))